server:
  port: 9500

spring:
  application:
    name: agg-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  path: logs/${spring.application.name}-${server.port}
  level:
    me.uc: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

feign:
  client:
    config:
      data-es:
        loggerLevel: FULL

